# Publish web app to github pages
name: Publish

on: 
  push:
    branches: [master, main]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy app to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          single-commit: true
          clean: true
